blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/josharsh/md-pdf-md/discussions/new?category=q-a
    about: Ask questions and discuss with the community
  - name: Show and Tell
    url: https://github.com/josharsh/md-pdf-md/discussions/new?category=show-and-tell
    about: Share what you've created with md-pdf-md
